###################################################################

# Created by write_sdc on Mon Sep 28 16:15:50 2026

###################################################################
set sdc_version 2.1

set_units -time ps -resistance kOhm -capacitance fF -voltage V -current mA
set_load -pin_load 5 [get_ports fifo_full_o]
set_load -pin_load 5 [get_ports fifo_empty_o]
set_load -pin_load 5 [get_ports {read_data_o[22]}]
set_load -pin_load 5 [get_ports {read_data_o[21]}]
set_load -pin_load 5 [get_ports {read_data_o[20]}]
set_load -pin_load 5 [get_ports {read_data_o[19]}]
set_load -pin_load 5 [get_ports {read_data_o[18]}]
set_load -pin_load 5 [get_ports {read_data_o[17]}]
set_load -pin_load 5 [get_ports {read_data_o[16]}]
set_load -pin_load 5 [get_ports {read_data_o[15]}]
set_load -pin_load 5 [get_ports {read_data_o[14]}]
set_load -pin_load 5 [get_ports {read_data_o[13]}]
set_load -pin_load 5 [get_ports {read_data_o[12]}]
set_load -pin_load 5 [get_ports {read_data_o[11]}]
set_load -pin_load 5 [get_ports {read_data_o[10]}]
set_load -pin_load 5 [get_ports {read_data_o[9]}]
set_load -pin_load 5 [get_ports {read_data_o[8]}]
set_load -pin_load 5 [get_ports {read_data_o[7]}]
set_load -pin_load 5 [get_ports {read_data_o[6]}]
set_load -pin_load 5 [get_ports {read_data_o[5]}]
set_load -pin_load 5 [get_ports {read_data_o[4]}]
set_load -pin_load 5 [get_ports {read_data_o[3]}]
set_load -pin_load 5 [get_ports {read_data_o[2]}]
set_load -pin_load 5 [get_ports {read_data_o[1]}]
set_load -pin_load 5 [get_ports {read_data_o[0]}]
create_clock [get_ports clk]  -period 10000  -waveform {0 5000}
set_clock_uncertainty 100  [get_clocks clk]
set_clock_transition -max -rise 20 [get_clocks clk]
set_clock_transition -max -fall 20 [get_clocks clk]
set_clock_transition -min -rise 20 [get_clocks clk]
set_clock_transition -min -fall 20 [get_clocks clk]
set_input_delay -clock clk  1000  [get_ports en_i]
set_input_delay -clock clk  1000  [get_ports wr_en_i]
set_input_delay -clock clk  1000  [get_ports rd_en_i]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[22]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[21]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[20]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[19]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[18]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[17]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[16]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[15]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[14]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[13]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[12]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[11]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[10]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[9]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[8]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[7]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[6]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[5]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[4]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[3]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[2]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[1]}]
set_input_delay -clock clk  1000  [get_ports {folded_history_i[0]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[22]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[21]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[20]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[19]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[18]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[17]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[16]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[15]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[14]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[13]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[12]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[11]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[10]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[9]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[8]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[7]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[6]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[5]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[4]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[3]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[2]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[1]}]
set_output_delay -clock clk  1000  [get_ports {read_data_o[0]}]
set_output_delay -clock clk  1000  [get_ports fifo_full_o]
set_output_delay -clock clk  1000  [get_ports fifo_empty_o]
set_input_transition -max 50  [get_ports rst_n]
set_input_transition -min 50  [get_ports rst_n]
set_input_transition -max 50  [get_ports en_i]
set_input_transition -min 50  [get_ports en_i]
set_input_transition -max 50  [get_ports wr_en_i]
set_input_transition -min 50  [get_ports wr_en_i]
set_input_transition -max 50  [get_ports {folded_history_i[22]}]
set_input_transition -min 50  [get_ports {folded_history_i[22]}]
set_input_transition -max 50  [get_ports {folded_history_i[21]}]
set_input_transition -min 50  [get_ports {folded_history_i[21]}]
set_input_transition -max 50  [get_ports {folded_history_i[20]}]
set_input_transition -min 50  [get_ports {folded_history_i[20]}]
set_input_transition -max 50  [get_ports {folded_history_i[19]}]
set_input_transition -min 50  [get_ports {folded_history_i[19]}]
set_input_transition -max 50  [get_ports {folded_history_i[18]}]
set_input_transition -min 50  [get_ports {folded_history_i[18]}]
set_input_transition -max 50  [get_ports {folded_history_i[17]}]
set_input_transition -min 50  [get_ports {folded_history_i[17]}]
set_input_transition -max 50  [get_ports {folded_history_i[16]}]
set_input_transition -min 50  [get_ports {folded_history_i[16]}]
set_input_transition -max 50  [get_ports {folded_history_i[15]}]
set_input_transition -min 50  [get_ports {folded_history_i[15]}]
set_input_transition -max 50  [get_ports {folded_history_i[14]}]
set_input_transition -min 50  [get_ports {folded_history_i[14]}]
set_input_transition -max 50  [get_ports {folded_history_i[13]}]
set_input_transition -min 50  [get_ports {folded_history_i[13]}]
set_input_transition -max 50  [get_ports {folded_history_i[12]}]
set_input_transition -min 50  [get_ports {folded_history_i[12]}]
set_input_transition -max 50  [get_ports {folded_history_i[11]}]
set_input_transition -min 50  [get_ports {folded_history_i[11]}]
set_input_transition -max 50  [get_ports {folded_history_i[10]}]
set_input_transition -min 50  [get_ports {folded_history_i[10]}]
set_input_transition -max 50  [get_ports {folded_history_i[9]}]
set_input_transition -min 50  [get_ports {folded_history_i[9]}]
set_input_transition -max 50  [get_ports {folded_history_i[8]}]
set_input_transition -min 50  [get_ports {folded_history_i[8]}]
set_input_transition -max 50  [get_ports {folded_history_i[7]}]
set_input_transition -min 50  [get_ports {folded_history_i[7]}]
set_input_transition -max 50  [get_ports {folded_history_i[6]}]
set_input_transition -min 50  [get_ports {folded_history_i[6]}]
set_input_transition -max 50  [get_ports {folded_history_i[5]}]
set_input_transition -min 50  [get_ports {folded_history_i[5]}]
set_input_transition -max 50  [get_ports {folded_history_i[4]}]
set_input_transition -min 50  [get_ports {folded_history_i[4]}]
set_input_transition -max 50  [get_ports {folded_history_i[3]}]
set_input_transition -min 50  [get_ports {folded_history_i[3]}]
set_input_transition -max 50  [get_ports {folded_history_i[2]}]
set_input_transition -min 50  [get_ports {folded_history_i[2]}]
set_input_transition -max 50  [get_ports {folded_history_i[1]}]
set_input_transition -min 50  [get_ports {folded_history_i[1]}]
set_input_transition -max 50  [get_ports {folded_history_i[0]}]
set_input_transition -min 50  [get_ports {folded_history_i[0]}]
set_input_transition -max 50  [get_ports rd_en_i]
set_input_transition -min 50  [get_ports rd_en_i]
set_false_path   -from [get_ports rst_n]
